# Generated by Django 5.2.6 on 2025-10-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_post_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
